In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
ROUTES_PATH = r"X:\00_ЛабГрад_ПО\09_Сотрудники\Глазов Ю.А\izhevsk\routes\yandex_izhevsk_28409.gpkg"

In [5]:
routes = gpd.read_file(ROUTES_PATH, layer='yandex_routes')
stops = gpd.read_file(r"X:\00_ЛабГрад_ПО\09_Сотрудники\Глазов Ю.А\izhevsk\routes\yandex_izhevsk_28409.gpkg", layer='yandex_stops')
isochrones = gpd.read_file(r"X:\00_ЛабГрад_ПО\09_Сотрудники\Глазов Ю.А\izhevsk\1_data\isochrones_result.gpkg")

In [6]:
stops_1 = stops[['ya_stop_id', 'ya_line_id','ya_route_id']].merge(isochrones[['point_id', 'intermodalnost']]
                                                                  .drop_duplicates(subset='point_id'), left_on='ya_stop_id',right_on='point_id', how='left')

In [7]:
routes = routes[routes['main_route'] == 'true']

In [8]:
stops_1['inter'] = (stops_1['intermodalnost'] > 0)

In [9]:
stops_1['inter'] = stops_1['inter'].fillna(0).astype(int)
stops_1

,ya_stop_id,ya_line_id,ya_route_id,point_id,intermodalnost,inter
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...","2161483940, 3960623020, 2161484061, 2161484004...",stop__9884354,6,1
1,stop__9884378,"2161483905, 2161483926, 3079437094, 2161483980...","2161483940, 3960623020, 3456270425, 3973084340...",stop__9884378,4,1
2,stop__9884383,"2161483905, 2161483942, 2161483909, 2161483912...","2161483940, 3960623020, 2161484052, 6063079379...",stop__9884383,0,0
3,stop__9884414,"2161483905, 2161483982, 2161483942, 2161483909...","2161483940, 3960623020, 2161484087, 2161484052...",stop__9884414,0,0
4,stop__9884444,"2161483905, 2161483953","2161483940, 3960623020, 2161484059",stop__9884444,2,1
...,...,...,...,...,...,...
683,stop__9884397,2161483903,3765179390,stop__9884397,2,1
684,stop__9884091,"2161483925, 3357137595","2161484017, 3357137945",stop__9884091,0,0
685,stop__9884380,"2161483925, 3357137595","3767018110, 3764809050",stop__9884380,0,0
686,3767017460,2161483925,3767018110,3767017460,0,0
687,3764629460,2161483979,"2172348372, 4849951386",3764629460,0,0

In [10]:
stops_1['ya_route_id'] = stops_1['ya_route_id'].astype(str).str.split(',')
stops_exploded = stops_1.explode('ya_route_id')
stops_exploded['ya_route_id'] = stops_exploded['ya_route_id'].str.strip()

In [11]:
stops_exploded

,ya_stop_id,ya_line_id,ya_route_id,point_id,intermodalnost,inter
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...",2161483940,stop__9884354,6,1
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...",3960623020,stop__9884354,6,1
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...",2161484061,stop__9884354,6,1
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...",2161484004,stop__9884354,6,1
0,stop__9884354,"2161483905, 2161483980, 2161483919, 2161483976...",2161484006,stop__9884354,6,1
...,...,...,...,...,...,...
685,stop__9884380,"2161483925, 3357137595",3767018110,stop__9884380,0,0
685,stop__9884380,"2161483925, 3357137595",3764809050,stop__9884380,0,0
686,3767017460,2161483925,3767018110,3767017460,0,0
687,3764629460,2161483979,2172348372,3764629460,0,0
687,3764629460,2161483979,4849951386,3764629460,0,0

In [12]:
result = (
    stops_exploded
    .groupby('ya_route_id')
    .agg(
        total_stops       = ('point_id', 'nunique'),   # всего уникальных остановок
        transfer_stops    = ('inter',       'sum'),       # из них пересадочных
    )
    .reset_index()
)

In [13]:
result

    ya_route_id  total_stops  transfer_stops
0    2161483920           26              26
1    2161483927           33               6
2    2161483936           14              14
3    2161483940           10               3
4    2161483943           15              15
..          ...          ...             ...
148  6541017682           28              28
149  6541028902            7               7
150  6541035752           21              21
151  6755267534            9               4
152  6829949084           38              15

[153 rows x 3 columns]

In [14]:
result['transfer_share'] = (
    result['transfer_stops'] / result['total_stops']
).round(3)

In [15]:
# routes['ya_route_id'] = routes['ya_route_id'].astype(str).str.strip()

result = result.merge(
    routes[['ya_route_id', 'route_name_with_vhc_prefix', 'ya_line_id']],
    on='ya_route_id',
    how='left'
)

# Переупорядочиваем столбцы
result = result[['ya_route_id', 'ya_line_id', 'route_name_with_vhc_prefix', 'total_stops', 'transfer_stops', 'transfer_share']]
result = result.sort_values('transfer_share', ascending=False).reset_index(drop=True)

result

,ya_route_id,ya_line_id,route_name_with_vhc_prefix,total_stops,transfer_stops,transfer_share
0,2161483920,2161483901,tramway_10,26,26,1.0
1,2161483936,2161483904,tramway_11,14,14,1.0
2,2161483943,2161483904,tramway_11,15,15,1.0
3,2161483949,2161483906,tramway_12,26,26,1.0
4,2161483993,2161483947,tramway_8,18,18,1.0
...,...,...,...,...,...,...
148,2161484089,NaN,NaN,17,0,0.0
149,5559412277,NaN,NaN,17,0,0.0
150,4206764043,2161483928,bus_16,24,0,0.0
151,6167904779,NaN,NaN,8,0,0.0
152,6207517119,NaN,NaN,18,0,0.0

In [16]:
route_to_line = result.groupby('ya_line_id').agg(
    name              = ('route_name_with_vhc_prefix',            'first'),
    num_variants      = ('ya_route_id',        'nunique'),     # сколько вариантов у маршрута
    total_stops       = ('total_stops',      'sum'),        # суммарное кол-во остановок
    transfer_stops    = ('transfer_stops',   'sum'),        # суммарное кол-во пересадочных
    transfer_share_mean = ('transfer_share', 'mean'),       # среднее по вариантам
    transfer_share_min  = ('transfer_share', 'min'),
    transfer_share_max  = ('transfer_share', 'max'),
).reset_index()

# Взвешенная доля (по числу остановок) — обычно корректнее простого среднего
route_to_line['transfer_share_weighted'] = (
    route_to_line['transfer_stops'] / route_to_line['total_stops']
).round(3) * 100

route_to_line = route_to_line.sort_values('transfer_share_weighted', ascending=False).reset_index(drop=True)

route_to_line

,ya_line_id,name,num_variants,total_stops,transfer_stops,transfer_share_mean,transfer_share_min,transfer_share_max,transfer_share_weighted
0,2161483899,tramway_1,2,50,50,1.0000,1.000,1.000,100.0
1,2161483901,tramway_10,2,52,52,1.0000,1.000,1.000,100.0
2,2161483915,tramway_4,2,41,41,1.0000,1.000,1.000,100.0
3,2161483904,tramway_11,2,29,29,1.0000,1.000,1.000,100.0
4,2161483908,tramway_7,2,40,40,1.0000,1.000,1.000,100.0
5,2161483906,tramway_12,2,52,52,1.0000,1.000,1.000,100.0
6,2161483966,tramway_5,2,64,64,1.0000,1.000,1.000,100.0
7,2161483947,tramway_8,2,35,35,1.0000,1.000,1.000,100.0
8,2161483950,tramway_9,2,56,56,1.0000,1.000,1.000,100.0
9,2161483932,tramway_2,2,47,47,1.0000,1.000,1.000,100.0
10,2161483959,tramway_3,1,20,20,1.0000,1.000,1.000,100.0
11,2161483974,trolleybus_6,1,42,29,0.6900,0.690,0.690,69.0
12,2161483909,bus_7,2,26,16,0.6150,0.538,0.692,61.5
13,2161483951,trolleybus_9,1,46,22,0.4780,0.478,0.478,47.8
14,2161483954,bus_28,2,44,18,0.4100,0.391,0.429,40.9
15,2161483913,bus_79,2,62,25,0.4040,0.375,0.433,40.3
16,2161483986,bus_25,2,76,30,0.3950,0.395,0.395,39.5
17,2161483942,bus_36,2,82,32,0.3925,0.364,0.421,39.0
18,2161483970,minibus_52,1,39,15,0.3850,0.385,0.385,38.5
19,2161483917,bus_40,2,40,15,0.3745,0.368,0.381,37.5
20,2161483924,bus_12,2,42,15,0.3570,0.350,0.364,35.7
21,2161483912,bus_73,2,31,11,0.3560,0.312,0.400,35.5
22,2161483905,bus_11,2,20,7,0.3500,0.300,0.400,35.0
23,2161483973,bus_56,2,73,24,0.3285,0.324,0.333,32.9
24,2161483989,bus_27,2,60,19,0.3165,0.300,0.333,31.7
25,2161483983,bus_22,2,80,25,0.3130,0.293,0.333,31.2
26,2161483957,bus_29,2,55,17,0.3135,0.267,0.360,30.9
27,2161483953,bus_9,2,23,7,0.3070,0.250,0.364,30.4
28,3079437094,bus_15к,2,30,9,0.3000,0.267,0.333,30.0
29,2161483979,trolleybus_2,2,47,13,0.2765,0.261,0.292,27.7
30,2161483980,bus_2,2,29,8,0.2765,0.267,0.286,27.6
31,2161483919,bus_41,2,26,7,0.2695,0.231,0.308,26.9
32,2161483926,bus_15,2,34,9,0.2645,0.235,0.294,26.5
33,3357137595,trolleybus_7,2,46,12,0.2615,0.250,0.273,26.1
34,2161483929,minibus_18,2,72,18,0.2520,0.231,0.273,25.0
35,2161483925,trolleybus_14,2,67,16,0.2395,0.229,0.250,23.9
36,2161483931,bus_19,2,50,11,0.2200,0.200,0.240,22.0
37,2161483976,bus_6,2,32,7,0.2190,0.188,0.250,21.9
38,2161483988,bus_26,1,67,14,0.2090,0.209,0.209,20.9
39,2161483903,trolleybus_10,2,66,13,0.1970,0.182,0.212,19.7
40,2161483900,trolleybus_1,2,41,8,0.1950,0.190,0.200,19.5
41,5166585596,minibus_66,2,56,10,0.1790,0.179,0.179,17.9
42,2161483982,bus_21,2,59,10,0.1695,0.167,0.172,16.9
43,2161483977,minibus_68,2,79,13,0.1645,0.150,0.179,16.5
44,6077430759,trolleybus_10д,2,81,12,0.1480,0.146,0.150,14.8
45,2161483914,bus_8,2,35,4,0.1145,0.111,0.118,11.4
46,2161483937,bus_34,2,43,4,0.0930,0.091,0.095,9.3
47,2161483964,bus_31,2,60,3,0.0500,0.033,0.067,5.0
48,2161483985,bus_23,1,36,1,0.0280,0.028,0.028,2.8
49,2161483928,bus_16,2,47,1,0.0215,0.000,0.043,2.1

In [17]:
routes = routes.merge(
    route_to_line[[
        'ya_line_id',
        'total_stops',
        'transfer_stops',
        'transfer_share_weighted',
        'transfer_share_mean',
    ]],
    on='ya_line_id',
    how='left'
)

In [102]:
routes.to_file(ROUTES_PATH, layer="lines_with_transfers", driver="GPKG")

In [18]:
routes

,ya_line_id,ya_route_id,ya_vhc_type,ya_route_name,route_name_with_vhc_prefix,file_name,start_stop_id,end_stop_id,start_stop_name,end_stop_name,...,3_class,8_uds,9_anchor,10_popul,2_start_time,geometry,total_stops,transfer_stops,transfer_share_weighted,transfer_share_mean
0,2161483905,2161483940,bus,11,bus_11,11,stop__9884354,stop__10061013,Ижевск – Собор Александра Невского,Улица Фурманова,...,3.0,32.0,2.0,2.0,5.0,"LINESTRING (9634444.857 6304730.034, 9634418.7...",20,7,35.0,0.3500
1,2161483905,2161483946,bus,11,bus_11,11,stop__9884455,stop__9884352,Улица Фурманова,Ижевск – Собор Александра Невского,...,3.0,32.0,2.0,2.0,5.0,"LINESTRING (9631958.022 6299080.08, 9631958.96...",20,7,35.0,0.3500
2,2161483924,2161483952,bus,12,bus_12,12,stop__9884357,stop__9884310,Станкострой,Автозавод - Разворотное кольцо,...,3.0,31.0,2.0,14.0,4.0,"LINESTRING (9633034.046 6304670.72, 9633036.20...",42,15,35.7,0.3570
3,2161483924,2161483955,bus,12,bus_12,12,stop__9884309,stop__9884357,Автозавод – Разворотное кольцо,Станкострой,...,3.0,31.0,2.0,14.0,4.0,"LINESTRING (9640668.133 6309216.425, 9640637.0...",42,15,35.7,0.3570
4,2161483926,2161484020,bus,15,bus_15,15,stop__9884471,stop__9884357,Металлобаза,Станкострой,...,3.0,57.0,2.0,4.0,5.0,"LINESTRING (9639115.503 6303107.303, 9639116.1...",34,9,26.5,0.2645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,3357137595,3357137945,trolleybus,7,trolleybus_7,tr7,3355529325,stop__9884082,Центр,Улица Труда,...,3.0,33.0,2.0,19.0,5.0,"LINESTRING (9634525.711 6304722.608, 9634516.3...",46,12,26.1,0.2615
90,3357137595,3764809050,trolleybus,7,trolleybus_7,tr7,stop__9884380,stop__9884351,Улица Труда,Центр,...,3.0,33.0,2.0,19.0,5.0,"LINESTRING (9639868.776 6306797.12, 9639862.82...",46,12,26.1,0.2615
91,2161483951,2161484058,trolleybus,9,trolleybus_9,tr9,stop__9884404,stop__9884109,Посёлок Машиностроителей,Городок Металлургов,...,3.0,31.0,2.0,18.0,5.0,"LINESTRING (9628966.413 6303341.049, 9628995.3...",46,22,47.8,0.4780
92,2161483942,6063076059,bus,36,bus_36,36,stop__9884229,stop__9884311,Микрорайон Нагорный,Завод пластмасс,...,3.0,28.0,2.0,29.0,5.0,"LINESTRING (9632982.617 6298689.604, 9632992.3...",82,32,39.0,0.3925
93,2161483942,6063079379,bus,36,bus_36,36,stop__9884312,stop__9884229,Завод пластмасс,Микрорайон Нагорный,...,3.0,28.0,2.0,29.0,5.0,"LINESTRING (9641248.147 6309457.474, 9641247.7...",82,32,39.0,0.3925